DDCE-3390: added origin to login urls
hmrc/maintain-beneficiaries-frontend pull request #262
Opened 2022-11-28 17:23 UTC by fraser-sprott

2022-12-07 11:22 UTC, ina-tu requested changes
needs a rebase

2023-01-05 16:12 UTC, anu9 commented
> needs a rebase

done

2023-01-09 10:05 UTC, ina-tu approved these changes

2023-01-10 13:38 UTC, ina-tu submitted a review, later dismissed
[conf/application-json-logger.xml](https://github.com/hmrc/maintain-beneficiaries-frontend/blob/DDCE-3390/conf/application-json-logger.xml) file is still needed

2023-02-02 17:23 UTC, zmdnoor approved these changes

2023-02-03 10:51 UTC, merged